#!/bin/bash
# 清理重複和過時的文檔檔案

echo "🗑️  開始清理重複的文檔..."

# YouTuber 推廣相關 - 刪除舊的，保留最新的
rm -f YOUTUBER_PROMOTION_COMPLETE.md
rm -f YOUTUBER_PROMOTION_FINAL_SUMMARY.md
rm -f YOUTUBER_PROMOTION_GUIDE.md
rm -f YOUTUBER_PROMOTION_INDEX.md
rm -f YOUTUBER_PROMOTION_IMPLEMENTATION_SUMMARY.md
rm -f YOUTUBER_PROMOTION_NEXT_STEPS.md
rm -f YOUTUBER_PROMOTION_QUICK_FIX.md
rm -f YOUTUBER_PROMOTION_SETUP_CHECKLIST.md
rm -f YOUTUBER_PROMOTION_SETUP.md
rm -f YOUTUBER_PROMOTION_SUMMARY.md
rm -f YOUTUBER_PROMOTION_TROUBLESHOOTING.md
rm -f YOUTUBER_PROMOTION_WORK_COMPLETED.md
rm -f YOUTUBER_PROMOTION_DIAGNOSIS.md
rm -f README_YOUTUBER_PROMOTION.md
rm -f START_YOUTUBER_PROMOTION_HERE.md
rm -f SOLUTION_SUMMARY.md

# Admin Auth 相關 - 合併為一個
rm -f ADMIN_AUTH_CHECKLIST.md
rm -f ADMIN_AUTH_COMPLETE.md
rm -f ADMIN_AUTH_IMPLEMENTATION_SUMMARY.md
rm -f ADMIN_AUTH_MIGRATION.md
rm -f ADMIN_AUTH_SETUP.md
rm -f ADMIN_PAGES_UPDATE.md
rm -f WORK_COMPLETED_ADMIN_AUTH.md
rm -f FINAL_IMPLEMENTATION_REPORT.md

# 下載功能相關 - 合併
rm -f CODE_EXAMPLES_DOWNLOAD_FEATURE.md
rm -f DOWNLOAD_FEATURE_CHECKLIST.md
rm -f DOWNLOAD_FEATURE_README.md
rm -f DOWNLOAD_STICKER_PACK_FEATURE.md
rm -f IMPLEMENTATION_SUMMARY_DOWNLOAD_FEATURE.md
rm -f INDEX_DOWNLOAD_FEATURE.md
rm -f QUICK_START_DOWNLOAD_FEATURE.md
rm -f VERIFICATION_DOWNLOAD_FEATURE.md
rm -f WORK_COMPLETED_DOWNLOAD_FEATURE.md
rm -f FINAL_SUMMARY_DOWNLOAD_FEATURE.md
rm -f FEATURE_COMPLETION_REPORT.md

# 貼圖內容修復相關
rm -f INDEX_STICKER_CONTENT_FIX.md
rm -f QUICK_FIX_STICKER_CONTENT.md
rm -f README_STICKER_CONTENT_FIX.md
rm -f STICKER_CONTENT_COMPLETE_FIX.md
rm -f STICKER_CONTENT_FIX_REPORT.md
rm -f STICKER_CONTENT_FIX_SUMMARY.md
rm -f STICKER_CONTENT_ISSUE_ANALYSIS.md
rm -f STICKER_FIX_CHECKLIST.md
rm -f VERIFICATION_STICKER_CONTENT_FIX.md
rm -f WORK_COMPLETED_STICKER_CONTENT_FIX.md
rm -f EXECUTIVE_SUMMARY_STICKER_FIX.md
rm -f FINAL_STICKER_CONTENT_REPORT.md

# 圖片品質相關
rm -f EXECUTIVE_SUMMARY_IMAGE_QUALITY.md
rm -f FINAL_IMAGE_QUALITY_FIX_SUMMARY.md
rm -f IMAGE_QUALITY_FIX_REPORT.md
rm -f IMAGE_QUALITY_FIXES_CHECKLIST.md
rm -f README_IMAGE_QUALITY_FIX.md
rm -f VERIFICATION_COMPLETE.md
rm -f WORK_COMPLETED_IMAGE_QUALITY.md

# 其他重複文檔
rm -f BUGFIX_SHARE_FEATURE.md
rm -f CHANGES_SUMMARY.md
rm -f CHECKLIST.md
rm -f CODE_COMPARISON.md
rm -f CONSISTENCY_FIX_REPORT.md
rm -f DEMO_GALLERY_CHECKLIST.md
rm -f DEMO_GALLERY_UPDATE.md
rm -f DEPLOYMENT_CHECKLIST.md
rm -f DEPLOYMENT_GUIDE.md
rm -f EXECUTE_NOW.md
rm -f EXECUTIVE_SUMMARY.md
rm -f FINAL_STATUS.md
rm -f FIX_SUMMARY.md
rm -f IMPROVEMENT_CHECKLIST.md
rm -f INDEX.md
rm -f MIGRATION_FIXED.md
rm -f PROMPT_COMPARISON.md
rm -f QUICK_REFERENCE_CARD.md
rm -f QUICK_REFERENCE.md
rm -f QUICK_START.md
rm -f REFACTORING_PLAN.md
rm -f REFACTORING_REPORT.md
rm -f SETUP_DEMO_GALLERY_DATABASE.md
rm -f SHARE_FEATURE_CHECK.md
rm -f START_HERE.md
rm -f VERIFICATION_REPORT.md
rm -f WHITE_SPOTS_ANALYSIS.md
rm -f WORK_COMPLETED.md

# 檢查清單文件
rm -f check-and-create-table.sql

echo "✅ 清理完成！"
echo ""
echo "保留的重要文檔："
echo "  📘 README.md - 主要說明文件"
echo "  📘 README_START_HERE.md - 快速開始指南"
echo "  📘 README_ADMIN_AUTH.md - 管理員認證"
echo "  📘 PROJECT_REPORT.md - 專案報告"
echo "  📘 PROJECT_SUMMARY.md - 專案總結"
echo "  📘 PROJECT_COMPLETION_SUMMARY.md - 完成總結"
echo "  📘 TROUBLESHOOTING.md - 故障排除"
echo "  📘 YOUTUBER_ADMIN_DEPLOYMENT.md - YouTuber 管理部署"
echo "  📘 YOUTUBER_ADMIN_SUMMARY.md - YouTuber 管理總結"
echo ""
echo "已刪除 70+ 個重複的文檔檔案"

